### ISSUE TITLE
Flamethrower + Medigun + Minigun + Other Weapon Sounds don't get overridden by weapon attributes

### ISSUE THREAD

**Issue by siobhan-saoirse** [Moddage/TF2-Gamemode#1]
Whenever you pick a weapon in the latest workshop update, like the weapons listed, the sounds are not overridden.

**Comment by siobhan-saoirse** [comment]
My only way to fix the issue is to make a duplicate of the original and modify it.

**Comment by LeadKiller** [comment]
fixed with commit https://github.com/Moddage/TF2-Gamemode/commit/0a42f471d0f125a439ed2d5ebb3d6e55f409aaec
